### ISSUE TITLE
Enable Win2D video effects

### ISSUE THREAD

**Issue by mmaitre314** [mmaitre314/VideoEffect#11]
Need a Win2D-equivalent of IBitmapVideoEffect for hardware-accelerated video effects in Bgra8 format.
See https://github.com/Microsoft/Win2D. Probably need to split the NuGet package into two to avoid pulling two other NuGet packages when not needed. ShaderEffectDefinitionXxx should go into the new Graphics package.

Tentative syntax:

class MyEffect : ICanvasVideoEffect
 {
     public void Process(CanvasBitmap input, CanvasRenderTarget output, TimeSpan time)
     {
             using (var ds = output.CreateDrawingSession())
             using (var brush = new CanvasImageBrush(input.device,input))
             {
                  ....
             }  
     }
 }

**Comment by venetasoft** [comment]
SUPPPPPPPPPER, can't wait :)
 
Thanks,
David
 
Date: Sun, 19 Apr 2015 00:40:36 -0700

**Comment by mmaitre314** [comment]
The implementation is checked in: cfd3f13b5834b644d040d32065ff4ed87f6194f3. I need to add more tests before publishing the NuGet.

**Comment by mmaitre314** [comment]
[2.3.0](http://www.nuget.org/packages/MMaitre.VideoEffects/2.3.0) is out with support for Win2D effects (aka CanvasEffect). I did some basic testing on Desktop and Lumia 520. Could you kick the tires on your side too, see if I didn't miss any major bug?

**Comment by venetasoft** [comment]
Thank you  !!!!!!! 
I will try immediately  :)
 
Dvaid
 
Date: Wed, 22 Apr 2015 23:02:06 -0700
