### ISSUE TITLE
VideoEffects.winmd' could not be found

### ISSUE THREAD

**Issue by xhhha123** [mmaitre314/VideoEffect#14]
Error	11	Metadata file 'C:\Users\admin\Downloads\VideoEffect-master\VideoEffects\Debug\VideoEffects.WindowsPhone\VideoEffects.winmd' could not be found	C:\Users\admin\Downloads\VideoEffect-master\VideoEffects\QrCodeDetector\QrCodeDetector.WindowsPhone\CSC	QrCodeDetector.WindowsPhone

**Comment by mmaitre314** [comment]
Could you give more details about your setup? Are the files present in the bin folders? Were the NuGet packages properly restored?

**Comment by xhhha123** [comment]
Hi mmaitre,

Here are my steps:
1.download the whole sln from github
2.open the solution VideoEffects.sln
3.open the package Manager Console and then download all the package, download successful.
4.Build the VideoEffects.sln
5.Get this error: Metadata file 'C:\Users\admin\Downloads\VideoEffect-master\VideoEffects\Debug\VideoEffects.WindowsPhone\VideoEffects.winmd' could not be found 

Actually I want to QrCodeDetector project to identify the QR code, want to know how should it work.

**Comment by xhhha123** [comment]
One more question, did the QrCodeDetector only support for x86 platform? Because I have Microsoft Lumia 750 and it is the x64 platform

**Comment by mmaitre314** [comment]
That's likely a problem: there is {x86, x64, arm32} for Windows and {x86, arm32} for Windows Phone. I didn't know VS2013 supported arm64. Are you using VS2015? The code should work for arm64 by rebuilding for that flavor. The Win2D and Lumia Imaging SDK might be missing that flavor too (I haven't checked). I imagine the Lumia 750 can run arm32 apps, so you could try that out?

**Comment by xhhha123** [comment]
Thanks a lot. After changing the x86 to ARM in configuration Manager, we could success to run the app in my Lumia.

**Comment by mmaitre314** [comment]
Closing old issue.
