### ISSUE TITLE
New Win2d lib on nuget

### ISSUE THREAD

**Issue by altima** [mmaitre314/VideoEffect#16]
Hi,

can you update the VideoEffects lib to use the new Win2D.win81 or Win2d.uwp packages from nuget?

http://www.nuget.org/packages/Win2D.win81
http://www.nuget.org/packages/Win2D.uwp

thanks.

**Comment by mmaitre314** [comment]
For UWP I was considering the VideoEffects lib to be obsolete since the OS now provides IBasicVideoEffect. Are there things that your app is doing with VideoEffects that it cannot do with IBasicVideoEffect?

**Comment by altima** [comment]
Ok, I dont know, because I use your lib only for a WP81 project and detecting some barcodes... So is it possible to update the videoeffects lib for the usage of Win2D.win81?

**Comment by mmaitre314** [comment]
I'll look into it tonight. That should be straightforward.

Sent from my Windows Phone
________________________________

**Comment by mmaitre314** [comment]
I just published v2.3.2 on nuget.org which switches to Win2D.win81. I also added a short paragraph in the Github doc about built-in OS support for video effects in Win10.

**Comment by altima** [comment]
thanks for the update :+1:
