### ISSUE TITLE
Whats the license status of this code?

### ISSUE THREAD

**Issue by pke** [mmaitre314/VideoEffect#18]
Hello,

I successfully improved the phonegap/cordova QR code scanner plugin using your awesome filter code here.
I'd like to open a pull-request for my improved version there but first I need to check with you about the license of your code.

Thanks!

**Comment by mmaitre314** [comment]
I used an apache 2 take-the-code-and-run license. If another license would work better in your case, I could update.

**Comment by pke** [comment]
Apache 2.0 is perfect! Thanks! Maybe you can add the license to the repo, so I can reference it in our app.

**Comment by mmaitre314** [comment]
It should be there already: https://github.com/mmaitre314/VideoEffect/blob/master/LICENSE
I am missing the standard header in source files though.
