### ISSUE TITLE
QRCode app constantly flashes focus assist light

### ISSUE THREAD

**Issue by pke** [mmaitre314/VideoEffect#20]
It seems there is no way to prevent the `focusAsync` method from using the focus assist flash (on my Lumi 925), is there?
The phone does not support the continuous focus feature it says. The nokia camera app however seems to be able to continuously focus. Does it use the same "trick" as you  here with refocusing every other second?

**Comment by mmaitre314** [comment]
My guess: the Nokia Camera app has access to proprietary driver controls that the QRCode app does not have access to. Disabling the flash in MediaCapture might prevent the focus assist flash (haven't tried).
