### ISSUE TITLE
[Questions] Understanding the code

### ISSUE THREAD

**Issue by pke** [mmaitre314/VideoEffect#21]
Thanks for the source! It helped me a lot to understand the video processing pipeline in MF.

I have several questions about certain implementation details:
## 1. CreateVideoProcessor

you commented 

> Create two different formats to force the SourceReader to create a video processor

What does that mean? Will the SourceReader not create a video processor if only one ouput format ist defined?
## 2. Why the arbitrary width & height values in VideoProcessor

You are using 640x480 for the first outputFormat and 800x600 for the second. Where do these values come from? Why did you choose those?
Will using the real cam preview width/height be more GPU friendly because no scaling would have to be applied.
## 3. "Length" parameter

From your sample app your hand in `640` as the "Length" parameter. Does it relate to the internal used values for the VideoProcessor in anyway?
## 4. Locks & Sync

I wonder why you not process every incoming frame in a thread? I have removed the `_processingSample` checks and it seems to run just fine, not sure if it improved the performance much because of the #20 issue.

Also why do you hold the `_analyzerLock` inside the `WorkItemHandler` and the `StartStreaming`. Because the workitemhandler could still be working when another `StartStreaming` is called? Can `StartStreaming` be called multiple times while filter is in the pipeline?
## 5. How to improve detection rate

Would using the native camera preview resolution improve detection rate of codes? I am asking cause it seems the detection rate could be better sometimes.
## 6. PropertySet

How would I fill a PropertySet from C++ code? It seems I cannot find any source code examples about this anywhere?

Thanks for taking your time to answer some or all those questions.

PS: I have used the relevant parts from your source code in my [QRScanner](https://github.com/pke/QrCodeScanner) test app (which will be used to improve the Cordova QR scanner plugin for Windows). Maybe I missed something. The detection rate seems worse than in your QRTest program

**Comment by mmaitre314** [comment]
1/2 CreateVideoProcessor() is a hack to work around the fact CLSID_VideoProcessorMFT was missed in the list of CLSIDs accessible to Store apps. Using different formats guarantees that the MFT gets inserted by SourceReader. There might be other ways to get that MFT inserted, but that one was good enough. SourceReader is actually not used, so width/height set there do not matter.

3 From a few tryouts, it looked like ZXing.NET has better detection rates when using frames with size around 640x480. I was initially thinking about using 320x240 but that was too small.

4 If ZXing detection runs faster than the preview fps, everything is fine. If not, frames pile up in from of the detector and after the queue becomes too long MediaCapture starts dropping preview frames. It's better to have the analyzer ignore frames: it avoids the preview latency added by the queue of frames.

The stream could be restarted while an image is analyzed. Skimming through the code I don't think the lock is a hard requirement. A few more member variables could be captured as lambda parameters.

5 It's possible. I don't think I tried. Preview resolution can go in the 720p on some phones and having ZXing.NET process that seemed a lot of computation.

6 I think that's what you are looking for: https://github.com/mmaitre314/VideoEffect/blob/3a6c26edcc4360e3a0db7a3c644a19733929fbb6/VideoEffects/VideoEffects/VideoEffects.Shared/LumiaAnalyzerDefinition.cpp

**Comment by pke** [comment]
Thanks for you quick answer. There is a `controller.flashControl.assistantLightEnabled` but it does nothing. I have disabled everything related to flash but it still flashes when focusing.

to 6. I tried that, yes. But when reading out the properties in the initializer raised a type exception. I will try again.

**Comment by mmaitre314** [comment]
A couple more things to try for flash:
- set FlashControl.Enabled to false
- set both flags to true and then to false (to force the command to go to the driver -- I recall a bug between MediaCapture and the driver in that area)

**Comment by pke** [comment]
About the focus assist light: I figured it out. https://github.com/pke/QrCodeScanner/commit/844ebac13287ec87182f2b38ea95b19636584c7f

Maybe the power=0 was the key. But I will try your solution too!
Thanks!

**Comment by pke** [comment]
about 6. I think there is no way to insert a JavaScript function (from within JS) to a PropertySet. I am getting a type mismatch 

```
var props = new Windows.Foundation.Collections.PropertySet();
                        props.insert("length", 640);
                        props.insert("oncode", function (event) {
                        });
```

In C# it somehow seems to work as demonstrated in your code. Any clue why?

**Comment by mmaitre314** [comment]
I don't think you can pass a JS function directly, but what you could do is pass an object which fires events or calls delegates (JS functions). The caller would new that object, register its JS functions as event/delegate callbacks on that object, and insert that object into the PropertySet. That's where xxxEffectDefinitions help: they can hide all that machinery from callers so only the effect author is confused.

There are some tricks because JS runs on the UI thread (aka ASTA) and MF runs on fairly random threads. There is some info about how to handle that in a JS-friendly way here: https://msdn.microsoft.com/en-us/library/windows/apps/dn169426.aspx .

**Comment by pke** [comment]
Yeah I fixed it already just like you suggested. From developing other WinRT components in the past I knew that we can call JS delegates only from the main thread. So I have to capture the UI Dispatcher and call the delegate through this. Combining this with XXXDefinition (which does the heavy plumbing indeed) everything works now!

**Comment by pke** [comment]
One more thing: Any idea why detecting data matrix codes is so difficult with Zxing? I have to really careful position the camera to get a valid reading.

**Comment by mmaitre314** [comment]
I only used ZXing with QR codes and UPCs, so not much experience with data matrix.

**Comment by pke** [comment]
I wanted to allow the user to specify the DecodeHints in the Definition like this:

``` cpp
using namespace Platform::Metadata;
        [Flags]
        public enum class BarcodeFormat : unsigned int {
            None = 0,
            QrCode = ::zxing::DecodeHints::BARCODEFORMAT_QR_CODE_HINT,
            DataMatrix = ::zxing::DecodeHints::BARCODEFORMAT_DATA_MATRIX_HINT,
            UPCE = ::zxing::DecodeHints::BARCODEFORMAT_UPC_E_HINT,
            UPCA = ::zxing::DecodeHints::BARCODEFORMAT_UPC_A_HINT,
            EAN8 = ::zxing::DecodeHints::BARCODEFORMAT_EAN_8_HINT,
            EAN13 = ::zxing::DecodeHints::BARCODEFORMAT_EAN_13_HINT,
            CODE128 = ::zxing::DecodeHints::BARCODEFORMAT_CODE_128_HINT,
            CODE39 = ::zxing::DecodeHints::BARCODEFORMAT_CODE_39_HINT,
            ITF = ::zxing::DecodeHints::BARCODEFORMAT_ITF_HINT,
            TryHarder = ::zxing::DecodeHints::TRYHARDER_HINT
        };

#if WINAPI_FAMILY!=WINAPI_FAMILY_PHONE_APP
        public interface class IVideoEffectDefinition {
            property Platform::String^ ActivatableClassId { Platform::String^ get(); }
            property Windows::Foundation::Collections::IPropertySet^ Properties { Windows::Foundation::Collections::IPropertySet^ get(); }
        };
#endif

        public ref class MultiFormatReaderDefinition sealed
#if WINAPI_FAMILY==WINAPI_FAMILY_PHONE_APP
            : public Windows::Media::Effects::IVideoEffectDefinition
#else
            : public IVideoEffectDefinition
#endif
        {
        public:
            MultiFormatReaderDefinition(BarcodeFormat formats, OnCodeHandler^ handler)
                : activatableClassId(L"org.zxing.BarcodeFilter")
                , properties(ref new Windows::Foundation::Collections::PropertySet()) {
                properties->Insert(L"oncode", handler);
                properties->Insert(L"formats", formats);
            }
            virtual property Platform::String^ ActivatableClassId {
                Platform::String^ get() {
                    return activatableClassId;
                }
            }

            virtual property Windows::Foundation::Collections::IPropertySet^ Properties {
                Windows::Foundation::Collections::IPropertySet^ get() {
                    return properties;
                }
            }

        private:
            Platform::String^ activatableClassId;
            Windows::Foundation::Collections::PropertySet^ properties;
        };
```

However, when I create the definition in JS like this:

``` js
var definition = org.zxing.MultiFormatReaderDefinition(org.zxing.BarcodeFormat.qrCode || org.zxing.BarcodeFormat.dataMatrix, function (code) {});
```

I always only get `QrCode(2)` handed into the definitions ctor. Any clue?

**Upps**: Nevermind, found the typo :/

**Comment by andr3aLucch3si85** [comment]
Hi. I don't understand how to stop the flash during the autofocus..Thanks!
