### ISSUE TITLE
Package not able to be installed

### ISSUE THREAD

**Issue by darylw** [mmaitre314/VideoEffect#22]
Hi,
This looks like the only real time video capture based solution that I can find - and I would like to be able to get it to work in my project, only when I try to add the nuget package it fails every time and rolls back.
The error I get is System.Xml.XmlException: '.', hexadecimal value 0x00, is an invalid character. Line 1, position 1. 
Unfortunately it doesn't say which file this is in, though to narrow it down, it fails directly after the LumiaImagingSDK installs. The sdk installs successfully, then it immediately rolls back after failing, stating that the Package 'Win2D.win81.1.4.0 : ' does not exist in folder xyz etc.

I am able to install several other packages into my project, so I don't think it's a project issue. I am running Visual Studio 2015 Community on Windows 10.

Any help with this is greatly appreciated.

**Comment by mmaitre314** [comment]
That does not ring a bell. Are you able to install Win2D and LumiaSDK on their own? If the NuGet does not work, another option would be to drop the lib code directly into your solution and build everything together.

**Comment by mmaitre314** [comment]
(hit the wrong button...)

**Comment by darylw** [comment]
Ok so if I install the win2d part manually from its own nuget package, then install the video effects package - it will work ok. (I did install the lumia sdk too, but the installation in your nuget overwrote it which is fine) So i am now at the point where it installs ok, so thank you for the suggestion of manually installing the components as that seems to work.
The previous issue seems like an issue with the win2d part of your nuget where it errors somewhere in the xml with an illegible character. That might be a red herring, or it could be the set up i am running.

**Comment by darylw** [comment]
Closing this issue - as solution is now working 99%
