### ISSUE TITLE
Orientation is always landscape regardless of specification

### ISSUE THREAD

**Issue by darylw** [mmaitre314/VideoEffect#23]
Hi,

I'm almost complete with this (99%), and I am so happy with the results - this is literally the ONLY realtime solution I have found for this, and it works like a charm. So my thanks and congratulations on the work that has gone into this thus far.

One small issue though that I can't quite work around, the line that reads: 
DisplayInformation.AutoRotationPreferences = DisplayOrientations.Landscape;

If I change this to be DisplayOrientations.Portrait instead - the view does not rotate which is great, but the preview inside is on its side, essentially landscape within a portrait view.

I have tried altering the preview and not gotten far with it. Is this solution not designed to be run in portrait mode, or have I just missed something? Is there any way that I could have the option of this displaying correctly in portrait mode as well as landscape mode if I rotated the device? Or just portrait if rotation is not able to work.

Any help is appreciated.

**Comment by mmaitre314** [comment]
Apologies for the slow response (I moved and the internet had a hard time moving with me...). From what I understand you want to rotate the capture preview. Take a look at SetPreviewRotationAsync() here: https://github.com/mmaitre314/MediaCaptureExtensions/blob/master/MediaCaptureExtensions/MediaCaptureExtensions.cs
Doing auto-rotation when the device is rotated is a bit more complex (depends on front vs back camera for instance), but if that's what you need I should be able to dig some sample code in the Windows Samples.

**Comment by sandrine-quadient** [comment]
Hi, 

I'd like to rotate the capture preview to portrait mode. 
I know we can rotate the MediaCapture with SetPreviewRotation function for example, but I don't know how to do this with CameraPreviewImageSource ?

Thank you for your help.

**Comment by mmaitre314** [comment]
Maybe use RotationEffect/RotationFilter since you are using the Lumia SDK?

**Comment by sandrine-quadient** [comment]
Yes thank you, I have found a solution using RotationFilter.

**Comment by darylw** [comment]
Hi sgo13 - I would be really interested in what you came up with for that, would you be able to share what you did with rotationFilter?

**Comment by darylw** [comment]
Issue resolved
