### ISSUE TITLE
Can not Run With Release Mode On Windows 10 UWP

### ISSUE THREAD

**Issue by renyg25** [mmaitre314/VideoEffect#27]
I am trying to run my UWP app which references the VideoEffects.Windows(Windows 8.1) project in release mode, but it always fails. The exception is 
"MCG0017: MCG0017:NotWinRTType Cannot marshal generic Windows Runtime types with a non Windows Runtime type as a generic type argument. Check the generic arguments of type 'Windows.Foundation.Collections.IIterable`1'. "

But it's working in Debug Mode, please help, thanks.

**Comment by mmaitre314** [comment]
I haven't tried running the code in Win10. Win10 has a built-in IBasicVideoEffect which makes the VideoEffect library mostly obsolete.

**Comment by renyg25** [comment]
Thank you for your response. 

Yes, Win 10 has built-in VideoEffects. But actually, I want to use the real-time to scan the bar code and qrcode. I use LumiaAnalyzerDefinition to return a bitmap from time to time. I am not able to use this function in Win 10 with Release Mode. Do you have any ideas? Thank you.

The codes are as follows,

VideoEffects.IVideoEffectDefinition definition = new LumiaAnalyzerDefinition(ColorMode.Yuv420Sp, 640, AnalyzeBitmap);
await capture.AddEffectAsync(MediaStreamType.VideoPreview, definition.ActivatableClassId, definition.Properties);

Then I can process the images from AnalyzeBitmap delegate. Any idea for Win 10 UWP to use it like this? Thanks.

**Comment by renyg25** [comment]
Hi, 

I've solved the problem. It was because I installed LumiaImageSDK.UWP.  It doesn't have the IFilter.  Now I reference the LumiaImageSDK which is the same with VideoEffects.Windows.
