### ISSUE TITLE
Very very slow (~2 FPS) MediaCapture camera preview when applying a QrCodeDetector effect

### ISSUE THREAD

**Issue by ahmedharmouche** [mmaitre314/VideoEffect#9]
Though ZXing can detect the code, the camera preview is very slow.

**Comment by mmaitre314** [comment]
The code is indeed quite inefficient. I can look into that. A few questions to better understand your scenario:
- Which device are you trying to run that on? 
- What is the preview resolution (MediaCapture.VideoDeviceController.GetMediaStreamProperties())?
- I assume you want to display the video preview in <CaptureElement> and overlay QR codes on top of that

Also, an alternative I have heard about was to use CameraStreamSource from the Lumia Imaging SDK: https://msdn.microsoft.com/en-us/library/dn859604.aspx
That might be worth giving it  a try.

**Comment by ahmedharmouche** [comment]
I run that on a Lumia 520, I'll check the preview resolution tomorrow. Yes, right, I want to do that. Barcode/QR code reading is a feature I have to implement in a shopping application. I didn't know when I started the development that It'd be an important feature, so I started a Windows Phone 8.1 Runtime project. If I'd have known I'm sure I had started a Silverlight project, so I could get easy access to camera preview. Thank You for creating this :) It really seems to be the only way for me to implement it. I wanted to make a custom MFT but I didn't know how to hack that together with ZXing. Do you think you can enhance VideoEffect, so I can use it? With the snippet you posted I actually got a "not bad" performance, but ZXing didn't decode anything. Than I set the AutoRotate and TryHarder properties to "true", and I could decode everything but with the mentioned performance. After that I only decoded on every 100th Process call, which wasn't bad, but still didn't feel comfortable. Please help me out I really need to get it done for this project, I can't port back to Silverlight, too large project.

**Comment by mmaitre314** [comment]
I just checked-in a "LumiaAnalyzer" class which should be more suited to that kind of task (less buffer copies/conversions + HW-accelerated scaling). Not much testing yet. I will try hooking that up with ZXing tomorrow and see what kind of perf that gives on 520. If that looks ok I'll publish a new NuGet.

**Comment by ahmedharmouche** [comment]
Wow, that'd be great! Thank you :)

Matthieu Maitre <notifications@github.com> ezt írta (2015. február 15.,
vasárnap):

**Comment by mmaitre314** [comment]
Things look better. NuGet 2.2.0 is out and doc was updated:
https://github.com/mmaitre314/VideoEffect#realtime-video-analysis-and-qr-code-detection

**Comment by ahmedharmouche** [comment]
Oh my goodness, this is lightning fast! You're the man! I told my boss that only a Microsoft engineer could help me out, and actually this is what happened! Thank you, thank you, thank you! I'll post your GitHub as answer for some StackOverflow questions :)

**Comment by ahmedharmouche** [comment]
Last questions: how can I set autofocus? how can I enable portrait mode and full screen?

**Comment by mmaitre314** [comment]
To set auto-focus:
```C#
var control = capture.VideoDeviceController.FocusControl;
if (control.SupportedFocusModes.Contains(FocusMode.Continuous) &&
    control.SupportedFocusRanges.Contains(AutoFocusRange.FullRange))
{
    control.Configure(new FocusSettings 
    { 
        Mode = FocusMode.Continuous, 
        AutoFocusRange = AutoFocusRange.FullRange 
    });
    await control.FocusAsync();
}
```
Lumia 520 does not have continuous auto-focus though. It only has one-time auto-focus, which is useful for taking photos but not really for scanning barcodes (unless somehow the user taps? or the app keeps on triggering auto-focus, but the preview will keep on scanning which is less than ideal).

For portrait mode you would need to either switch that line to portrait (fixed UI orientation) or remove it (auto-rotate UI):
```c#
DisplayInformation.AutoRotationPreferences = DisplayOrientations.Landscape;
```
In general using a fixed UI orientation is much simpler with camera preview, especially in landscape (hence why I lock that to landscape in pretty much all the code samples I write).

Fixed portrait UI requires a 90 degree rotation. MediaCapture does not make that easy (at least when trying to avoid black bars all around). Here is some code doing that:
https://github.com/mmaitre314/MediaCaptureExtensions/blob/master/MediaCaptureExtensions/MediaCaptureExtensions.cs

Auto-rotate UI requires changing rotation on the fly.

For full screen preview the simplest is to ask `CaptureElement` to stretch:
```xml
<CaptureElement Name="Preview" Stretch="Uniform"/>
```
(or `UniformToFill`)

Alternatively for QR code I used `ScaleTransform` along with `ActualWidth` and `ActualHeight` from `Page`, but that's 10-20px too small. `Window.Current.Bounds` might be a better choice (I haven't tried that).

```C#
var scale = Math.Min(this.ActualWidth / format.Width, this.ActualHeight / format.Height);
Preview.Width = format.Width;
Preview.Height = format.Height;
Preview.RenderTransformOrigin = new Point(.5, .5);
Preview.RenderTransform = new ScaleTransform { ScaleX = scale, ScaleY = scale };
```

**Comment by ahmedharmouche** [comment]
Thank you! I rotated with this: capture.SetPreviewRotation(VideoRotation.Clockwise90Degrees); than set CaptureElement to UniformToFill and I don't have black bars around it, so it works.

**Comment by ahmedharmouche** [comment]
When I navigate to the QRCode reader page, and navigate back and repeate it 10 times, but sometimes only 5 times the program crashes. Maybe something goes wrong when disposing capture? The crash always happens when i navigate back, so something in OnNavigatedFrom is wrong. Could you help me?

**Comment by mmaitre314** [comment]
I am about to leave on vacation, so just giving some quick tip. I don't think the code I wrote handle enough events, the back button in particular. Here is the events handlers I have seen in other code:
App_Suspending
HardwareButtons_BackPressed
Camera_Failed
SystemMediaControls_PropertyChanged (Desktop only)

**Comment by ahmedharmouche** [comment]
Thank you! It seems like the problem was the inproper dispose of mediacapture, now it looks like: 

if (m_capture != null)
            {
                await m_capture.StopPreviewAsync();

                if (Preview != null)
                {
                    Preview.Source = null;
                }

                m_capture.Dispose();
                m_capture = null;
            }

It works, doesn't freeze any more.

**Comment by johny1234** [comment]
I am working on windows phone 8.1 universal app and facing below issue for QR code scanning 
I generate QR code from this website https://www.the-qrcode-generator.com/
and then I capture the image with phone using MediaCapture class  and decode the QR code using zxing decoder
It works fine as long as the string length i used to generate qr code is around 180, 
But beyond that Zxing decoder is not able to decode the QR code,

**Comment by mmaitre314** [comment]
That's more a question for ZXing. I haven't checked what is its length limitation.

**Comment by johny1234** [comment]
Actually the problem arises when image is captured using MediaCapture class  and then the same image is given to decoder in writeablebitmap form(which is expected input).
It seems the quality of the image captured using MediaCapture is not upto the mark for a QR code.
I have taken care of resolution overriding i.e. selecting the maximum resolution, AutoFocus.

But if same QR image i copy from https://www.the-qrcode-generator.com/ where i am generating QR code, and feed it to QR decoder after converting it to writeable bitmap it works fine.
var file = await Windows.ApplicationModel.Package.Current.InstalledLocation.GetFileAsync(@"Assets\QRimage.png");

**Comment by mmaitre314** [comment]
When I was putting that code together I hit detection-rate issues which were due to bad handling of image stride. One thing you could try is to save to png file, load it back, and run detection on it. Checking the png file should show if there is any stride issue. Besides that, it's quite likely camera image quality is not as high as ZXing would like. ZXing seems to be sensitive to image blur, so maybe a sharpening filter may help (I haven't tried). It's typically better to use byte[] as input of ZXing than writeablebitmap, but more from a perf point of view than quality.

**Comment by johny1234** [comment]
thanks for reply,
Have tried both things already, saving to png as well and using byte[] as input, but no luck

**Comment by GotaloveCode** [comment]
So I am trying to reuse your code so the capture starts on button click captureelement is set visible.Now my challenge is stopping the capture in AnalyzeBitmap am trying to call DisposeCaptureAsync to stop the camera capture but its not working.Below is my code.Any assist is highly appreciated.@mmaitre awesome code library.Fastest qr reader available online so far.Thanks for sharing this library.

//code ommitted for brevity inside AnalyzeBitmap()

```
 for (int n = 0; n < result.ResultPoints.Length; n++)
                    {
                        BarcodeOutline.Points.Add(new Point(
                            result.ResultPoints[n].X * (BarcodeOutline.Width / bitmap.Dimensions.Width),
                            result.ResultPoints[n].Y * (BarcodeOutline.Height / bitmap.Dimensions.Height)
                            ));
                    }
                    //cleanup
                     Dispatcher.RunAsync(CoreDispatcherPriority.Normal, async () =>
                    {
                        await DisposeCaptureAsync();

                    });
```
